### ISSUE TITLE
Server Crashed: Invalid array length

### ISSUE THREAD

**Issue by nbriz** [brangerbriz/wifi-data-safari#17] opened 2018-04-02 20:51 UTC
```
[info] airodump-ng process exited
[info] tcpdump process exited
[info] stopping wlan0mon interface with airmon-ng
/home/nbriz/BRANGER_BRIZ/wifi-data-safari/server.js:66
		throw err
		^

RangeError: Invalid array length
    at padLeft (/home/nbriz/BRANGER_BRIZ/wifi-data-safari/src/utils.js:6:9)
    at AirodumpParser._isRandomMAC (/home/nbriz/BRANGER_BRIZ/wifi-data-safari/src/AirodumpParser.js:210:12)
    at nets.forEach (/home/nbriz/BRANGER_BRIZ/wifi-data-safari/src/AirodumpParser.js:52:24)
    at Array.forEach (native)
    at AirodumpParser.parseCSV (/home/nbriz/BRANGER_BRIZ/wifi-data-safari/src/AirodumpParser.js:27:9)
    at fs.readFile (/home/nbriz/BRANGER_BRIZ/wifi-data-safari/src/AirodumpParser.js:146:39)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
```

**Comment by brannondorsey** [comment] 2018-04-03 15:30
Duplicate of #16.

**Closed as completed by brannondorsey** 2018-04-03 15:30 UTC
Labels: bug
